services:
  db:
    image: postgres:latest
    volumes:
      - ./src/db/db-setup.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    ports: 
      - 5432:5432
    secrets:
      - pg_password
  app:
    image: node:22  
    user: node
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PGUSER=postgres
      - PGPASSWORD=/run/secrets/pg_password
      - PGHOST=db
      - PGDATABASE=Calisthenics
    command: sh -c "npm i && npm run dev"
    depends_on:
      - db
    init: true
    ports:
      - 3000:3000
      - 9229:9229
    secrets:
      - pg_password

secrets:
  pg_password: 
    file: ./src/db/password.txt

