export const steps = [
  {
    headerText: 'Jumping jacks',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: -1,
    nextId: 1,
  },
  {
    headerText: 'Wrist warmup',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 0,
    nextId: 2,
  },
  {
    headerText: 'Burpees',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 1,
    nextId: 3,
  },
  {
    headerText: 'Arm warmup',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 2,
    nextId: 4,
  },
  {
    headerText: 'Legs',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 3,
    nextId: 5,
  },
  {
    headerText: 'Push',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 4,
    nextId: 6,
  },
  {
    headerText: 'Pull',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 5,
    nextId: 7,
  },
  {
    headerText: 'Rest',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 6,
    nextId: 8,
  },
  {
    headerText: 'Legs',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 7,
    nextId: 9,
  },
  {
    headerText: 'Push',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 8,
    nextId: 10,
  },
  {
    headerText: 'Pull',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 9,
    nextId: 11,
  },
  {
    headerText: 'Rest',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 10,
    nextId: 12,
  },
  {
    headerText: 'Legs',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 11,
    nextId: 13,
  },
  {
    headerText: 'Push',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 12,
    nextId: 14,
  },
  {
    headerText: 'Pull',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 13,
    nextId: 15,
  },
  {
    headerText: 'Rest',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 14,
    nextId: 16,
  },
  {
    headerText: 'Legs',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 15,
    nextId: 17,
  },
  {
    headerText: 'Push',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 16,
    nextId: 18,
  },
  {
    headerText: 'Pull',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 17,
    nextId: 19,
  },
  {
    headerText: 'Rest',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 18,
    nextId: 20,
  },
  {
    headerText: 'Legs',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 19,
    nextId: 21,
  },
  {
    headerText: 'Push',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 20,
    nextId: 22,
  },
  {
    headerText: 'Pull',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 21,
    nextId: 23,
  },
  {
    headerText: 'Sun salutation',
    image: './src/images/jumping-jacks.jpg',
    inputValue: 6,
    inputType: 'none',
    buttonText: 'Done',
    previousId: 22,
    nextId: -1,
  },
];
